version: '3.1'

networks:
  todonet:
    driver: bridge

services:
  todo:
    image: index.docker.io/cage1016/gokit-todo:latest
    depends_on:
      - db
    environment:
      QS_DB_HOST: db
      QS_DB_PORT: 5432
      QS_DB_USER: postgres
      QS_DB_PASS: password
      QS_DB: todo
    restart: on-failure
    networks:
      - todonet

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    networks:
      - todonet

  web:
    image: index.docker.io/cage1016/gokit-todo-frontend-dev:latest
    depends_on:
      - todo
    restart: on-failure
    networks:
      - todonet

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:80
      - 10120:10120
    networks:
      - todonet

#  Web client             Nginx       Web Server      API          DB
#  <http request>   <-->  8000  <-->  80
#  <http request>   <------------------------------>  10120  <-->  5432
